[package]
name = "nfa-rust-contracts"
version = "0.0.1"
description="Rust contracts to mint NonFungibleAchievements on the Solana chain"
authors = ["Landon Boles <ldb@erikboles.com>"]
repository="https://github.com/TheLDB/NonFungibleAchievements"
license="MIT"
homepage="nonfungibleachievements.xyz"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.9.1"
solana-program = "~1.8.14"

[dev-dependencies]
solana-program-test = "~1.8.14"
solana-sdk = "~1.8.14"

[lib]
name = "nfa-rust-contracts"
crate-type = ["cdylib", "lib"]